### ISSUE TITLE
Multiple bets in a game from same wallet

### ISSUE THREAD

**Issue by AayeshaShrestha** [RedChillies-Core/BetGame#12]
**Bug Description**
A user can create multiple bets in same game from same wallet.
Betting from host address is possible. 

**Expected Behavior**
1. Host should not be allowed to bet.
2. One bet per game per wallet. 

**Video or screenshots**
Bets 1 and 2 have same gameId
![Screenshot from 2021-03-18 13-51-32](https://user-images.githubusercontent.com/28928754/111594197-db89ab00-87f2-11eb-96d7-393110f19eb6.png)

HostId and BettedById are same. 
![Screenshot from 2021-03-18 13-52-07](https://user-images.githubusercontent.com/28928754/111594385-1a1f6580-87f3-11eb-8482-103b01b92d78.png)

**Comment by bibek54** [comment]
This has been fixed as. well
