### ISSUE TITLE
What happens when you pass already existing betId while betting?

### ISSUE THREAD

**Issue by AayeshaShrestha** [RedChillies-Core/BetGame#13]
**Bug Description**
When you pass already existing betId while creating a bet, the existing values are replaced by new ones. 
This is handled in frontend but we should check it here as well. What if we don't pass betId from frontend and set some random number in SC itself? 

**Steps to recreate**
1. Create two games with ids 123 and 1234.
2. Create a bet. `Params gameId: 123, betId: 1, betSelected: 1`-> logs value as 
```
1: { 
...bet1Details 
gameId: 123
}
```
3. Create another bet. `Params gameId: 1234, betId: 1, betSelected: 0` -> replaces above 1 as 
```
1: { 
...bet1Details 
gameId: 1234
}
```
So there’s no record of the first bet. 
This happens when you pass same betId for same game as well. 

**Video or screenshots**

**Comment by bibek54** [comment]
Yeah I got this issue. Can you check it once in new contract? Must have been fixed
