### ISSUE TITLE
Redeem Issue

### ISSUE THREAD

**Issue by AayeshaShrestha** [RedChillies-Core/BetGame#14]
You can redeem unverified game by passing wrong gameId.

Screenshots for more clarity.
a. Bet 1 is on game 1234.
![Screenshot from 2021-03-18 15-39-24](https://user-images.githubusercontent.com/28928754/111607369-45f51800-8800-11eb-8950-f2be59b981f7.png)
b. Game 1234 has status 2 (unverified)
![Screenshot from 2021-03-18 15-39-58](https://user-images.githubusercontent.com/28928754/111607502-691fc780-8800-11eb-8d27-75b19284dc45.png)
c. betStatus if bet 1 is 1 (redeemed)
![Screenshot from 2021-03-18 15-39-36](https://user-images.githubusercontent.com/28928754/111607573-7c329780-8800-11eb-9e41-d5a9b999a55c.png)

**Steps to recreate:**
1. Create two games 123 and 1234. 
2. Place bets on games 123 and 1234 by different wallet addresses.
3. Change game 123 to verified (gameStatus: 3)  by performing necessary steps. So game_123 has status 3 and game_1234 has status 2 (resultFlashed).
4. Now use wallet address that has betted in game 1234. And redeem, while redeeming, pass gameId: 123 (wrong id but it is verified). User should not be able to redeem since is it not verified. But user is able to redeem.

**Comment by bibek54** [comment]
Not able to reproduce this. Can you check once. again?
